### ISSUE TITLE
`GZDoom 4.6.1` | `Gearbox 0.6.0` Getting a VM abort for `wheel` and `block` selector types when running with Hexen/Heretic only and selecting inventory items.

### ISSUE THREAD

**Issue by awgv** [mmaulwurff/gearbox#17] opened 2021-08-30 11:26 UTC
Hello,

Plain text selector for inventory items and weapon selection for all selector types seem to be working as expected. Here’re the screenshots of both aborts: 1) [wheel](https://i.imgur.com/zaRlSP4.png); 2) [block](https://i.imgur.com/d00E76r.png). Both selectors work when there’re no items in the inventory, but then immediately throw when there’s at least one and I try to open Gearbox to select something. Tried `give all` to see how it behaves with full inventory and it also throws at the same lines.

Thank you for your time.

**Comment by mmaulwurff** [comment] 2021-08-30 12:10
Duplicate of  #15, fixed in 042ba9990.

**Closed by mmaulwurff** 2021-08-30 12:10 UTC
Labels: duplicate
